"""chat history, made messages field a list by default

Revision ID: 16d7b932685f
Revises: b4cc1ee063f9
Create Date: 2025-08-01 00:15:28.711677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d7b932685f'
down_revision: Union[str, Sequence[str], None] = 'b4cc1ee063f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
