"""chat history, messeages field changed from JSON to mutable list

Revision ID: 3caac6ce072e
Revises: 843f50ff953e
Create Date: 2025-08-01 00:26:43.146787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3caac6ce072e'
down_revision: Union[str, Sequence[str], None] = '843f50ff953e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
