"""new enums are appended for feynman level

Revision ID: 546434906a63
Revises: 6106b8bae2af
Create Date: 2025-08-05 19:42:59.929769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "546434906a63"
down_revision: Union[str, Sequence[str], None] = "6106b8bae2af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("chat_history_note_id_fkey"), "chat_history", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("chat_history_document_id_fkey"), "chat_history", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "chat_history", "notes", ["note_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "chat_history", "documents", ["document_id"], ["id"], ondelete="CASCADE"
    )
    op.execute("ALTER TYPE chatmodeenum ADD VALUE IF NOT EXISTS 'feynman_child'")
    op.execute("ALTER TYPE chatmodeenum ADD VALUE IF NOT EXISTS 'feynman_student'")
    op.execute("ALTER TYPE chatmodeenum ADD VALUE IF NOT EXISTS 'feynman_prof'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_history", type_="foreignkey")
    op.drop_constraint(None, "chat_history", type_="foreignkey")
    op.create_foreign_key(
        op.f("chat_history_document_id_fkey"),
        "chat_history",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("chat_history_note_id_fkey"),
        "chat_history",
        "notes",
        ["note_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
