"""new modes added into chat mode enum

Revision ID: 6106b8bae2af
Revises: 3caac6ce072e
Create Date: 2025-08-02 13:16:30.072205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6106b8bae2af"
down_revision: Union[str, Sequence[str], None] = "3caac6ce072e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE chatmodeenum ADD VALUE IF NOT EXISTS 'feynman'")
    op.execute("ALTER TYPE chatmodeenum ADD VALUE IF NOT EXISTS 'debate'")
    op.execute("ALTER TYPE chatmodeenum ADD VALUE IF NOT EXISTS 'cases'")
    op.execute("ALTER TYPE chatmodeenum ADD VALUE IF NOT EXISTS 'reflect'")
    op.execute("ALTER TYPE chatmodeenum ADD VALUE IF NOT EXISTS 'editor'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
