"""chat history, messeages field changed from JSON to mutable list

Revision ID: 843f50ff953e
Revises: 16d7b932685f
Create Date: 2025-08-01 00:23:02.538911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843f50ff953e'
down_revision: Union[str, Sequence[str], None] = '16d7b932685f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
