"""content added to Note table

Revision ID: 98579df84dde
Revises: 7d1b69e620dd
Create Date: 2025-07-30 21:18:46.602742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98579df84dde'
down_revision: Union[str, Sequence[str], None] = '7d1b69e620dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content', sa.String(), nullable=True))
    op.create_index(op.f('ix_notes_content'), 'notes', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_content'), table_name='notes')
    op.drop_column('notes', 'content')
    # ### end Alembic commands ###
