"""tables have changed

Revision ID: d89697315790
Revises: 
Create Date: 2025-07-29 00:18:43.436049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89697315790'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('note_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('chat_history_user_id_fkey'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'notes', ['note_id'], ['id'], ondelete='SET NULL')
    op.drop_column('chat_history', 'user_id')
    op.add_column('documents', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'workspace_id')
    op.add_column('chat_history', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_user_id_fkey'), 'chat_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_history', 'note_id')
    # ### end Alembic commands ###
